### PR TITLE
feat(installer) Windows powershell installer and uninstaller

### PR DESCRIPTION
**Pull request by MeguminSama**
Installer and Uninstaller for windows (powershell)

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
I can't really verify this, but your scripts only target the stable discord client
What if I only have discord PTB?

**Comment by MeguminSama** [comment]
> I can't really verify this, but your scripts only target the stable discord client What if I only have discord PTB?

The normal install script only does stable, so I copied that into this script

**Comment by ArjixWasTaken** [comment]
no that is wrong, you can rename the discord-ptb command to be just discord
so any client version is supported, as long as the executable on PATH is named discord

**Comment by MeguminSama** [comment]
Working on adding a branch selector

**Comment by MeguminSama** [comment]
:)
image

**Comment by Vendicated** [comment]
LGTM probably idk I never did pwsh

**Pull request merged**
