### PR TITLE
showHiddenThings: also show ModView & hidden discovery servers

### PR DESCRIPTION
**Pull request by dolfies**
This kinda steps on the toes of the user functionality in PermissionsViewer
jmjadwQPSn 1

### CODE REVIEW

**Comment by dolfies** [comment]
This now also removes algolia filters that hide servers that don't meet the requirements from discovery <:blobcatcozy:1145727546747535412>

**Comment by Golonchy** [comment]
very cool :)

**Comment by Vendicated** [comment]
of course the alien wants to see everything in the human world 👽 

thanks again

**Comment by dolfies** [comment]
💚

**Pull request merged**
