### PR TITLE
Remove safari compatibility tag

### PR DESCRIPTION
**Pull request by itz-coffee**
Removing it out of the userscript because of https://github.com/Vendicated/Vencord/issues/1417#issuecomment-1646371117

### CODE REVIEW

**Comment by Vendicated** [comment]
no
grafik

**Comment by itz-coffee** [comment]
I don't know what that is a screenshot of but I am on safari 17.0 (like your picture has it green as) and it doesn't work, you said it yourself that it doesn't work on safari so why keep it?

**Comment by Vendicated** [comment]
it should work on more recent safari versions. it only doesn't work on the old versions

**Comment by itz-coffee** [comment]
Still not working for me but I'll just move to vencord desktop

Trying to get it to work with "userscripts" (safari clone of tampermonkey) but won't work, I did buy tampermonkey couple months ago but refunded it since same issue. Didn't know it worked for others so I won't keep bugging

**Comment by Vendicated** [comment]
it probably works with tampermonkey or violentmonkey if those exist for safari. i don't own a mac, and never used safari in my life so i can't test it but there's no reason it shouldn't

**Pull request closed without merging**
