### PR TITLE
feat(plugins/moreCommands): add skill issue command

### PR DESCRIPTION
**Pull request by isabelroses**
I think people would love this.
A simple and small command.

Example:
image

### CODE REVIEW

**Comment by h4rldev** [comment]
This would be really funny

**Comment by TheKodeToad** [comment]
honestly I think this gets old really quickly lol

**Comment by isabelroses** [comment]
> honestly I think this gets old really quickly lol

Yeah it probably could but better that it there for anyone that still finds it useful etc.

**Comment by h4rldev** [comment]
Ngl a figlet command would be better

**Comment by Vendicated** [comment]
pretty funny but you can just achieve this with text replace so it's not that useful

**Pull request closed without merging**
