### PR TITLE
ViewIcons: Fix animated server pfps & profile edit button

### LINKED ISSUE #1236: [Bug] viewIcons plugin: the "View Server Avatar" button never returns GIFs
### Discord Account

Lumap#0001

### What happens when the bug or crash occurs?

When a member has an animated server avatar, right-clicking on their profile and clicking server avatar only shows the webp version of their avatar instead of the GIF one

### What is the expected behaviour?

a GIF avatar is shown instead

### How do you recreate this bug or crash?

1. Have a member with an animated server avatar
2. Right click -> View server avatar

### Errors

_No response_

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

### PR DESCRIPTION
**Pull request by Commandtechno**
fixes #1236

### CODE REVIEW

**Comment by Commandtechno** [comment]
also fixed the errors when you right clicked a folder

**Comment by Commandtechno** [comment]
also fixed the bug where clicking edit profile pulled up the banner

image

**Comment by sup-Udh** [comment]
wait does thie let the user have animated pfp? 
@Vendicated  @Commandtechno

**Comment by DaBluLite** [comment]
no

**Comment by Commandtechno** [comment]
this is for the viewIcons plugin that allows you to click on images like avatar and banner, when clicking on an animated server pfp it brought up a static one which this fixed

**Pull request merged**
