### PR TITLE
feat: anonymous telemetry

### PR DESCRIPTION
**Pull request by lewisakura**
Depends on https://github.com/Vencord/Vencloud/pull/20

Collecting information about:
- Vencord versions in use
- Plugins in use
- Operating systems in use

This will not be traced back to a user.

**ONLY MERGE IF COMMUNITY APPROVAL IS GAINED. HEAVILY WORK IN PROGRESS.**

### CODE REVIEW

**Comment by FieryFlames** [comment]
🤓☝️ you need to remove "no telemetry" from the readme

**Review by Zippybonzo — APPROVED** [review]
My quick lookthrough shows it's pretty good. - I would say don't send it on devbuilds so uncomment that but it seems good beyond that.

**Comment by lewisakura** [comment]
> My quick lookthrough shows it's pretty good. - I would say don't send it on devbuilds so uncomment that but it seems good beyond that.

We aren't going to send on devbuilds, it's to be added back before this gets merged (if it does) but it needs to be commented during testing.

**Review by thororen1234 — APPROVED** [review]
looks cool and could be used for debugging n stuff even tho the user will complain but it could help listing errors as in if a certain error keeps popping up its high priority ect.

**Comment by IThundxr** [comment]
Telemetry 👍 👍

**Review by IThundxr — APPROVED** [review]
Yummy

**Review by taskylizard — APPROVED** [review]

**Comment by lewisakura** [comment]
No motivation to continue doing this from our side at the minute, so it's on hold until further notice.

**Pull request closed without merging**
