### PR TITLE
added uwuify, but correct

### PR DESCRIPTION
**Pull request by exhq**

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Look at [lenny](https://github.com/Vendicated/Vencord/blob/main/src/plugins/lenny.ts), that is the recommended way of adding commands.

**Comment by exhq** [comment]
thanks, ill look into it :)

**Comment by ArjixWasTaken** [comment]
LGTM, although I wouldn't iterate over each character, is there a particular reason that you did it that way?

**Comment by exhq** [comment]
> LGTM, although I wouldn't iterate over each word, is there a particular reason that you did it that way?

check the if statements. I'm uwuifying them by some rules, tho they're simple but they prevent words from being over-uwuified and being unreadable

for example, if we have uwu as the input, without the checks, it'd become "uwuwuwu"

**Comment by ArjixWasTaken** [comment]
this is how i'd refactor this
```javascript
const endings = [
    "owo",    "UwU",
    ">w<",    "^w^",
    "●w●",    "☆w☆",
    "𝗨𝘄𝗨",    "(´꒳`)",
    "♥(。U ω U。)",
    "(˘ε˘)",    "*screams*",
    "*twerks*",    "*sweats*",
]; 

let text = "Hello there, how are you?"

Array.from(text.matchAll(/[A-Za-z]+/g)).map(([word]) => {
    if (/[OU]w[OU]/.test(word)) return [word, word];
    let uwuified = word;
    if (word.includes("u")) uwuified = word.replace("u", "UwU");
    else if (word.includes("o")) uwuified = word.replace("o", "OwO");

    if (Math.floor(Math.random() * 2) == 1) uwuified = uwuified.replace("s", "sh");
    if (Math.floor(Math.random() * 5) == 3) uwuified += " " + endings[Math.floor(Math.random() * endings.length)];
    
    return [word, uwuified.replace(/(?<=[^rl])[rl](?!][^rl])/g, "w")];
}).map(([a, b]) => text = text.replace(a, b))

console.log(text)
```

**Comment by exhq** [comment]
that doesnt include the word replacements, also you missed a few checks

**Comment by ArjixWasTaken** [comment]
also, the letter o or u may not exist in a word, but you change `isOwo` to true either way, so you ignore some words

**Comment by ArjixWasTaken** [comment]
> checking if the word has been already uwuified

lmao, you don't know how to chain if statements together?

```javascript
if (true) {}
else if (true) { /* this wont run, because the previous if condition was true */ }
```

**Comment by ArjixWasTaken** [comment]
since you split on space
image

words like `love!` wont be replaced, because `"love!" != "love"`

**Comment by exhq** [comment]
somewhat intentional. to prevent over-uwufying

**Comment by exhq** [comment]
> > checking if the word has been already uwuified
> 
> lmao, you don't know how to chain if statements together?
> 
> ```js
> if (true) {}
> else if (true) { /* this wont run, because the previous if condition was true */ }
> ```

that is actually something I missed in my code. i have to check for isowo in at least have of the statements to again, prevent overuwuifying

**Comment by ArjixWasTaken** [comment]
If I were you I'd move the if statements that don't use `isOwo` up, and just return instead of relying on `isOwo`

**Comment by ArjixWasTaken** [comment]
@Vendicated don't merge until the line count is at 69 once again

**Comment by exhq** [comment]
when merge:tm:

**Comment by ArjixWasTaken** [comment]
When the line count is at 69 once again

**Comment by exhq** [comment]
i will literally steal your cock

**Comment by ArjixWasTaken** [comment]
You can reduce the line count by removing the newlines in the endings array

**Comment by somerandomcloud** [comment]
Reading these comments was a rollercoaster. Plinko, I guess

**Comment by ArjixWasTaken** [comment]
day 2 of not having exactly 69 lines of code :(

**Comment by exhq** [comment]
vendy can you just merge please i feel like ive been edging for a week now, it hurts

**Comment by ArjixWasTaken** [comment]
instead of reducing the line count, this mf increased it
this PR will never get merged ig

**Review by Vendicated — APPROVED** [review]

**Comment by ArjixWasTaken** [comment]
noooooooooooo

**Pull request merged**
