### PR TITLE
Updater: Axios Update

### PR DESCRIPTION
**Pull request by thororen1234**
This update makes the client updater use axios. this makes a lot of things easier such as the requests in general as http is outdated.

### CODE REVIEW

**Comment by thororen1234** [comment]
scratch the http is outdated was just told otherwise after they told me it was outdated 😭 
either way I feel axios is better over all!

**Comment by MrDiamondDog** [comment]
What was wrong with it before? I see no reason to change this

**Comment by nyakowint** [comment]
Why do this just to be added to devs? It works fine as is lol

**Comment by Vendicated** [comment]
axios is extremely bloated

**Pull request closed without merging**
