### PR TITLE
moreUserTags: Ability to customize text inside tag & settings design overhaul

### PR DESCRIPTION
**Pull request by LordEliasTM**

### CODE REVIEW

**Comment by ActuallyTheSun** [comment]
the settings menu now with all the tag options is a mess. 2 options for every tag, and it doesn't even look good

what about remaking it with a custom component? so the settings are in one place for the tag, and they dont look like 💩 
i'll probably make it and open a pr on the fork

**Comment by LordEliasTM** [comment]
Agreed, didn't like how messy it is either. Double fork sounds good 👍

**Comment by ActuallyTheSun** [comment]
LordEliasTM/Vencord#1

also can i just add #811 here :trollface:

**Comment by LordEliasTM** [comment]
> also can i just add https://github.com/Vendicated/Vencord/pull/811 here :trollface:

Sure lol

**Comment by LordEliasTM** [comment]
@ActuallyTheSun i made use of tooltips. The description right under the name looked a bit off
image

**Comment by LordEliasTM** [comment]
ready to merge now

**Comment by LordEliasTM** [comment]
accidentally deleted the branch 💀

**Pull request closed without merging**
