### PR TITLE
feat(plugin): add MessageLinkEmbeds

### PR DESCRIPTION
**Pull request by ActuallyTheSun**
plugin to show message links as embeds in chat
image

### CODE REVIEW

**Comment by Vendicated** [comment]
would be way cooler if you made it render as actual Message Components instead

**Comment by ActuallyTheSun** [comment]
i did not realize that could be done
great idea

**Comment by Vendicated** [comment]
it definitely can be done, just have to fetch the right components and figure out how to render them properly based on the fetched message

Cyn had a cumcord plugin that does this, it is outdated now but can still be used as reference
https://gitlab.com/Cynosphere/cumcord-plugins/-/tree/master/MessageLinkPreview

**Comment by ActuallyTheSun** [comment]
yeah, i have no idea where to even start with that (mainly because i barely know what i am doing) and im fairly sure i need to completely rewrite this to show as a message
i'll just close the pr and return when i can figure out how to do that

**Pull request closed without merging**
