### PR TITLE
Fart plugin

### PR DESCRIPTION
**Pull request by ItzOnlyAnimal**
It is inevitable :trollface:

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
So you request from someone to fart...but you fart before they can even reply?

You should instead play the fart sound when the person you asked says "farted"

**Comment by ItzOnlyAnimal** [comment]
Good eye, however you take the assumption that the person will comply, so no waiting is required.

**Review by botatooo — COMMENTED** [review]
what, what happened in iLoveSpam

**Comment by MeguminSama** [comment]
> what, what happened in iLoveSpam

Moving author to author list instead of repeating it in every plugin

**Comment by botatooo** [comment]
oh nvm its the same person

**Review by Vendicated — APPROVED** [review]

**Comment by Vendicated** [comment]
please fart conflicts

**Comment by ItzOnlyAnimal** [comment]
conflicts have been farted :trollface:

**Comment by Vendicated** [comment]
Looks fart to me

**Comment by MeguminSama** [comment]
fart

**Pull request merged**
