### PR TITLE
Feat(plugin): KeywordAlerts

### PR DESCRIPTION
**Pull request by Captain8771**
This plugin adds Alerts (also known as "Highlights") when someone sends a keyword.

Preview: 
image
image

As always, feel free to suggest any changes, or report any bugs that I missed.
If a maintainer makes a change on this PR, please ping me in the discord (@Captain#3175) so I don't make the same mistake I made with CustomRPC

###### PS: This plugin is a shitshow internally.

### CODE REVIEW

**Comment by Captain8771** [comment]
shit i pinged someone again, sorry other captain

**Comment by castdrian** [comment]
the title seems a bit intrusive I feel like it should just be the username, maybe channel and guild, something useful instead of all caps KEYWORD ALERT BY <user>, furthermore you could probably integrate this into the inbox as additional tab next to mentions

**Comment by Captain8771** [comment]
> the title seems a bit intrusive I feel like it should just be the username, maybe channel and guild, something useful instead of all caps KEYWORD ALERT BY , furthermore you could probably integrate this into the inbox as additional tab next to mentions

the uppercasing is not something done by the plugin, as can be seen [here](https://github.com/Vendicated/Vencord/blob/6bbd6ffc2a74a9d3a771e4cde078ab9753cd4278/src/plugins/keywordAlert.tsx#L144), but the title could indeed be upgraded a bit. As for integrating it into the inbox, I'm gonna look into that.

**Comment by castdrian** [comment]
since you said in discord that inbox is breaking your noggin, maybe just some modal that lists highlights as clickable message components or something, just to like have a history type of thing-ish situation

**Comment by Captain8771** [comment]
> since you said in discord that inbox is breaking your noggin, maybe just some modal that lists highlights as clickable message components or something, just to like have a history type of thing-ish situation

hmm. interesting. only one problem: Where would I put it? I considered settings, as a button, but that's 3 layers deep and likely annoying.

perhaps up here?
image

**Comment by castdrian** [comment]
yeah that seems like the most reasonable spot, surely there's gotta be some nice SVG that represents a highlight

**Comment by Captain8771** [comment]
could probably make one myself

**Review by mantikafasi — APPROVED** [review]
merge

**Comment by Captain8771** [comment]
no not yet I haven't even done the svg yet

**Comment by mantikafasi** [comment]
do it and I will force ven to merge

**Comment by Captain8771** [comment]
you act like i have a clue what im doing 
image

**Comment by mantikafasi** [comment]
idk I write random stuff and it usually works

do the same

**Comment by Captain8771** [comment]
i mean if you want to you can do the svg, unless there's a built in SVG that fits

**Comment by Captain8771** [comment]
@mantikafasi since you wanted that \^ enjoy

**Comment by mantikafasi** [comment]
Thank you

**Comment by Captain8771** [comment]
I should probably mark this as draft until it's done

**Comment by ItzOnlyAnimal** [comment]
Should make it ignore the message if it already pings the user

**Comment by Captain8771** [comment]
That is a possibility too.

and maybe even ignore [at]silent maybe?

**Comment by mantikafasi** [comment]
stop sending emails to me and finish the goddamn plugin

**Comment by waheedullahkhan001** [comment]
ummm
1. The test are failing hehe
2. Please add regex support it should be easy and it will be kewl

**Comment by waheedullahkhan001** [comment]
Bump.
I have been waiting for this one for a long time.

**Comment by Captain8771** [comment]
> Bump. I have been waiting for this one for a long time.

Currently waiting on #696 for the sweet sweet arrays, as separating by `,` isn't ideal for the user. 

> Please also add regex support.

That is also planned, and #696 will also add OptionType.REGEX

**Comment by ArjixWasTaken** [comment]
> Currently waiting on https://github.com/Vendicated/Vencord/pull/696 for the sweet sweet arrays, as separating by , isn't ideal for the user.

Could have just used a custom component, but yee, sweet sweet arrays.

**Comment by Vendicated** [comment]
closing due to age since this has been a draft for ages and is likely not being worked on anymore. If you still want to work on this, feel free to just reopen whenever!!

Thank you anyway!

**Pull request closed without merging**
