### PR TITLE
Add plugin: Viewy

### PR DESCRIPTION
**Pull request by Bonkeyzz**
I made a plugin which allows a user to view another user's avatar (or user-specific avatars) and stickers.

_~~Might need a better name for it.~~_

### CODE REVIEW

**Comment by Captain8771** [comment]
is this not already a thing?

**Comment by Bonkeyzz** [comment]
> is this not already a thing?

Yeah, currently it has similar functionality to ViewIcons. But i wanna make this like BetterDiscord's ImageUtilities over time.

**Comment by TheKodeToad** [comment]
Wouldn't it still be weird to have duplicate functionality?

**Comment by Bonkeyzz** [comment]
Redundant now, functionality implemented by updated versions of Vencord from plugins: ViewIcons & ImageZoom.

**Pull request closed without merging**
