### PR TITLE
feat(plugin) cartineseTranslator - funny cartinese message translator

### PR DESCRIPTION
**Pull request by brandonapt**
silly little cartinese message translator. 

<3

### CODE REVIEW

**Comment by moxie-coder** [comment]
google translate plugin already exists

**Comment by Oi-jojo** [comment]
epic 😎

**Comment by Oi-jojo** [comment]
could you add a toggle feature like the translate plugin that sits on your text bar, thank you, amazing plugin

**Comment by Oi-jojo** [comment]
> google translate plugin already exists

read the read.ME, it takes your text and makes it look funkier but still somewhat quessible to the other person what you want to say

**Comment by lewisakura** [comment]
why

**Pull request closed without merging**
