### PR TITLE
feat(ViewIcons): Group & User DMs icons support

### PR DESCRIPTION
**Pull request by verticalsync**
Lets you view the icon of group channel icons by adding an entry in the context menu called "View Icon".

image
image

### CODE REVIEW

**Comment by Vendicated** [comment]
thanks for the contribution!

would be useful to also make this image clickable
image

**Comment by verticalsync** [comment]
> thanks for the contribution!
> 
> would be useful to also make this image clickable image

I'll try, I've never really made my own patches, and I thought of this before.

**Comment by verticalsync** [comment]
Yeah I haven't been able to figure it out sorry I'm too inexperienced with patches 😭, but if anyone wants to add it go ahead it's also possible for the user icons when you open a dm next to name I guess.

**Comment by Nuckyz** [comment]
> Yeah I haven't been able to figure it out (couldn't find the thing to patch) sorry I'm too inexperienced with patches 😭, but if anyone wants to add it go ahead it's also possible for the user icons when you open a normal dm next to username I guess.

I did it for you

**Comment by Nuckyz** [comment]
Thank you for the new feature!

**Comment by verticalsync** [comment]
> > Yeah I haven't been able to figure it out (couldn't find the thing to patch) sorry I'm too inexperienced with patches 😭, but if anyone wants to add it go ahead it's also possible for the user icons when you open a normal dm next to username I guess.
> 
> I did it for you

Thank you 🙏

**Pull request merged**
