### PR TITLE
feat(plugin): DevilBro's memory leak simulator

### PR DESCRIPTION
**Pull request by X1nto**
Also updates BANger to use Xinto constant from utils

### CODE REVIEW

**Comment by Ruthenic** [comment]
If you want more control of the size you can just make a bunch of uintarrays or whatever they're called

**Comment by Ruthenic** [comment]
See [Pee.js](https://github.com/enbyautumn/pee.js)

**Comment by X1nto** [comment]
> If you want more control of the size you can just make a bunch of uintarrays or whatever they're called

I don't think I'll ever need that, as I want the plugin to do more than just fill up memory (such as crashing and freezing, which it already does now)

**Comment by MeguminSama** [comment]
it has to do it in a stylish and epic and pro gamer way

**Comment by exhq** [comment]
so true

**Comment by Ruthenic** [comment]
> > If you want more control of the size you can just make a bunch of uintarrays or whatever they're called
> 
> I don't think I'll ever need that, as I want the plugin to do more than just fill up memory (such as crashing and freezing, which it already does now)

That's fair but if you allocate like a million megabytes i'm pretty sure the app is gonna crash and burn no matter what you do

**Comment by X1nto** [comment]
> That's fair but if you allocate like a million megabytes i'm pretty sure the app is gonna crash and burn no matter what you do

I think that is fine unless maybe @Vendicated wants me to change that

**Comment by somerandomcloud** [comment]
Vouch

**Pull request closed without merging**
