### PR TITLE
whoReacted: fix reaction count being off by one

### PR DESCRIPTION
**Pull request by WackyModer**
## Before:

how it worked before

## After:

how it should look

it didn't break anything

proof that it didn't break anything

I *did* put myself in `src/utils/constants.ts` (and not the `whoReacted` plugin contributors) but feel free to remove me from it if this contribution is too small.

### CODE REVIEW

**Comment by WackyModer** [comment]
I hope `dev2` was the correct branch to be committing to...

**Comment by lewisakura** [comment]
dev is the correct base, not dev2

**Comment by WackyModer** [comment]
> dev is the correct base, not dev2

Thank you for rebasing it. So what is dev2 meant for then?

**Comment by lewisakura** [comment]
dev2 is a branch we can directly commit to and merge into dev later

**Comment by WackyModer** [comment]
Thanks for telling me that, you might want to add that to the contributing.md (unless this is standard practice)

**Comment by Vendicated** [comment]
thanks!

**Pull request merged**
