### PR TITLE
Plugin: 7TV

### PR DESCRIPTION
**Pull request by Xslash58**
This plugin allows you to browse emotes from [7TV](https://7tv.app) and send them.

 

Also displays [7TV](https://7tv.app) badges, if enabled

### CODE REVIEW

**Comment by xseba2137** [comment]
A very cool thing! When it's in the app, I'll use it! 🔥🔥👌👌✌️👍👍
image

**Comment by xMufaro** [comment]
i like the idea, would use it so much

**Comment by ArjixWasTaken** [comment]
could have had a server with them emotes + fakenitro

**Comment by ArjixWasTaken** [comment]
If you need to properly integrate with discord's gif/sticker/emoji picker, you can copy our patches from #992 

[Code for the patches](https://github.com/ArjixWasTaken/Vencord/blob/MoreStickers/src/plugins/moreStickers/index.tsx#L47-L97)

That way you won't need to open a modal, and it would look better.

image

Just make sure to not have conflict with our plugin.

**Comment by ArjixWasTaken** [comment]
I can help you modify the patches if you want.

**Comment by Xslash58** [comment]
> I can help you modify the patches if you want.

I moved the modal to the emoji picker but I have 2 problems here, maybe you can help:
1) I don't know how to move the "7TV" tab in the picker after the "Emoji" so it won't conflict with your plugin. If I try to move it after the "Emoji" tab, it somehow moves outside the nav entirely. 
2) I don't know how to open the picker with the "7TV" tab opened. (Basically, how to make icon work)

And Is there a better way to refresh the view after emotes are fetched other than reopening it?

I work on this [branch](https://github.com/Xslash58/Vencord/tree/7TVEmotes-emojipicker) for now.

**Comment by ArjixWasTaken** [comment]
I attached the code on discord.

**Comment by ArjixWasTaken** [comment]
`searching == false`?
Really?

Why not just `!searching`?

**Comment by ArjixWasTaken** [comment]
I'd suggest making the picker to be an infinite scroll instead of pagination.

**Comment by Xslash58** [comment]
> I'd suggest making the picker to be an infinite scroll instead of pagination.

I can't request all emotes from 7TV. That's why there's a pagination

**Comment by Xslash58** [comment]
I've made an infinite scroll on [this](https://github.com/Xslash58/Vencord/tree/7TVEmotes-infinitescroll) branch.
But tbh I like the pages more. It's more similar to the 7TV website and you can specify how many emotes you want to see per page. My friend agreed with that too. I'd rather leave the pages.

**Comment by KrDimitrov** [comment]
why this not merged :(

**Pull request closed without merging**
