### PR TITLE
feat(themes): Online theme toggles

### PR DESCRIPTION
**Pull request by MrDiamondDog**
Allows for toggling online themes without messing with them in the text box

image

### CODE REVIEW

**Comment by D3SOX** [comment]
I'm suggesting these changes
- add remove buttons to the themes
- remove the text box above entirely
-  instead add a field to add a new one above with a button that fetches the theme and then only adds it if it's valid

Do you want to implement them, or should I give it a chance?

**Comment by MrDiamondDog** [comment]
Yeah I would love to do that, first I have to fix all my other prs that are prob broken now

**Comment by MrDiamondDog** [comment]
dw i messed up the branch, this pr will be coming back soon

**Comment by MrDiamondDog** [comment]
Reopened in #1929

**Pull request closed without merging**
