### PR TITLE
feat(Plugin): BlurNSFW+ (Up-to-date fork of BlurNSFW)

### PR DESCRIPTION
**Pull request by MiguVT**
This is a fork of BlurNSFW, works as BlurNSFW, but its a separate plugin because it have some extra options that are not neccesary in a simple plugin like BlurNSFW+. I will be adding more options in that days.
imagen

### CODE REVIEW

**Comment by surgedevs** [comment]
..Why?

Also its insane to remove Ven from authors when 95% of the code is copied from Ven...

**Comment by MiguVT** [comment]
> ..Why?
> 
> Also its insane to remove Ven from authors when 95% of the code is copied from Ven...

I mentioned in the description but i dont remember to add Ven, will ad rn, one moment

**Comment by MiguVT** [comment]
done, tysm <3

**Comment by surgedevs** [comment]
> done, tysm <3

Still, why?

The nature of Vencord allows anyone to contribute to any plugin, if you really want your changes in Vencord I suggest just adding the options to the original BlurNSFW. <Plugin>+ is very stupid.

**Comment by MiguVT** [comment]
> > done, tysm <3
> 
> Still, why?
> 
> The nature of Vencord allows anyone to contribute to any plugin, if you really want your changes in Vencord I suggest just adding the options to the original BlurNSFW. (Plugin)+ is very stupid.

My idea was making a different plugin because i dont saw any update in BlurNSFW, at the start i made the changes in the original plugin, but i made it different when saw the last update is 9 months ago and i wanted to make it like an "BlurNSFW plugin with more options", because some people would like simple plugin without excesive options, i can do it in the main plugin if there is no problem to add too much options in the future

**Pull request closed without merging**
