### PR TITLE
Added a warning about using PS

### PR DESCRIPTION
**Pull request by okunamayanad**
Added a warning about Windows 11 Terminal app automatically choosing PowerShell instead of Command Prompt

### CODE REVIEW

**Comment by Vendicated** [comment]
why would it not work in powershell

**Comment by okunamayanad** [comment]
> why would it not work in powershell

```
PS C:\Users\baran\AppData\Local\Temp\vencordinstall\Vencord> pnpm i
pnpm : File C:\Users\baran\AppData\Roaming\npm\pnpm.ps1 cannot be loaded because running scripts is disabled on this sy
stem. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ pnpm i
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Users\baran\AppData\Local\Temp\vencordinstall\Vencord> pnpm build
pnpm : File C:\Users\baran\AppData\Roaming\npm\pnpm.ps1 cannot be loaded because running scripts is disabled on this sy
stem. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ pnpm build
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by ArjixWasTaken** [comment]
You just need to change the execution policy

**Comment by ArjixWasTaken** [comment]
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force
```

**Pull request closed without merging**
