### PR TITLE
Add option to ignore incoming blocked messages

### PR DESCRIPTION
**Pull request by somerandomcloud**
Pros: Conversation with yourself doesn't look ugly (not dissing noBlockedMessages, but yknow)
Cons: Wont work when a channel is refreshed or all messages are grabbed for the first time

[saul.webm](https://user-images.githubusercontent.com/39058370/198891279-6b118d51-30b0-4024-b44a-59dbca31052c.webm)

### CODE REVIEW

**Comment by Luna-devv** [comment]
[ski-ba-bop-ba-dop-bop_wacked..webm](https://user-images.githubusercontent.com/71079641/198891940-9485398e-95ee-403e-b5f1-5ff48a9d5176.webm)

**Comment by somerandomcloud** [comment]
Bhop

**Comment by somerandomcloud** [comment]
[cat_shrink.webm](https://user-images.githubusercontent.com/39058370/198898056-fa3c856c-c118-4dca-8807-02c80f34a828.webm)

**Comment by somerandomcloud** [comment]
Is there any update on this? I know I said it was doodoo dogshit but I hate open prs and there has been no conversation on this

**Comment by Vendicated** [comment]
oh my god

**Pull request merged**
