### PR TITLE
Use a tiny character (˞) instead of emoji's name

### PR DESCRIPTION
**Pull request by JagTheFriend**
The message itself will appear cleaner.

### CODE REVIEW

**Comment by Grafaffel** [comment]
just change it in the plugins setting

**Comment by Sqaaakoi** [comment]
...this will break stuff more.

**Comment by Vendicated** [comment]
yeah you changed the wrong code

and this is already a native feature of the plugin, just change the format in its settings 
image

**Comment by JagTheFriend** [comment]
> yeah you changed the wrong code
> 
> and this is already a native feature of the plugin, just change the format in its settings image

Ohk, I didn't know

**Pull request closed without merging**
