### PR TITLE
ReplaceGoogleSearch: improve search engine selection

### PR DESCRIPTION
**Pull request by OtterCodes101**

### CODE REVIEW

**Comment by KrstlSkll69** [comment]
Isn't this what the custom search engine is for?
(_also adding your self to devs for a two line change is wild_)
Capture

**Comment by KrstlSkll69** [comment]
Ok, I'm going to assume you are a NTTS kid, also just as the main dev of this plugin Moxxie said "Things like AOL, Kagi, Banidu where added as a joke and a funny haha"

**Comment by KrstlSkll69** [comment]
Thats actually not a bad idea, and it actually wouldn't be that much of a pain

**Comment by Kodarru** [comment]
Couldn't we turn the const in a var so we can edit it, rename it and allow the user to delete and add search engines?

**Comment by Kodarru** [comment]
Then the client could fetch the image url to use via the favicon

**Pull request merged**
