### PR TITLE
[GlobalBadges] New Plugin

### PR DESCRIPTION
**Pull request by HypedDomi**
### Supported client mods:

- Aliucord
- BetterDiscord
- Enmity
- Replugged
- Velocity

### CODE REVIEW

**Comment by Vendicated** [comment]
why

**Comment by HypedDomi** [comment]
> why

IDK. Seemed like a cool plugin idea

**Comment by SomeAspy** [comment]
is there a reason why this was denied

**Comment by ywxweal** [comment]
bruh

**Comment by Vendicated** [comment]
> is there a reason why this was denied

Badges are a way to denote people who contributed in certain ways, whether that be via contributing, donating or possible more ways

Adding badges from all mods combined is counter-intuitive, slightly confusing and also fairly pointless

**Comment by SomeAspy** [comment]
Thank you for the clarification

**Pull request closed without merging**
