### PR TITLE
Contributor Cards: Add display names

### PR DESCRIPTION
**Pull request by lumap**
~~This plugin also requires a hacky way to update the discord-types package to include the globalName property, as a version with it hasn't been pushed to npm.~~ fuck it, type any

### CODE REVIEW

**Comment by Vendicated** [comment]
image

**Comment by lumap** [comment]
> image

i love html, it's so great

**Comment by Vendicated** [comment]
I'm not sure this is a good addition. for me personally, this looks way worse than just having the username

**Comment by lumap** [comment]
i think having just the username feels kinda weird, especially when discord has display names as well as usernames everywhere throughout the app

**Comment by Vendicated** [comment]
i still think this looks very bad

**Comment by lumap** [comment]
cba to rewrite since rspack + useless

**Pull request closed without merging**
