### PR TITLE
feat(plugin): DMPresets

### PR DESCRIPTION
**Pull request by nmsturcke**
Create your own presets to reply to recurring questions in DMs with one click.

## Demonstration

https://github.com/Vendicated/Vencord/assets/30734036/ee22cbe5-a9f1-448c-991e-34e86b95a47e

### CODE REVIEW

**Comment by Vendicated** [comment]
this is essentially just a second MessageTags

**Comment by MrDiamondDog** [comment]
MessageTags basically does this

**Comment by TheKodeToad** [comment]
If you wanted a UI version (why) you could just add a button next to the message box

**Comment by nmsturcke** [comment]
Oh.. Hadn't seen it 😔

**Pull request closed without merging**
