### PR TITLE
feat(themes): Online Themes Redesign

### PR DESCRIPTION
**Pull request by MrDiamondDog**
Redesigns the Online Themes menu to be more user-friendly and easy to use.

image
image

### CODE REVIEW

**Comment by D3SOX** [comment]
Looks good, but upon trying it locally I found a bug where it doesn't display the themes.
Console spits out `OnlineThemes.tsx:66 Uncaught (in promise) Not a CSS file. Remember to use the raw link!`
I think it's because I'm using a theme from a URL that redirects (this still works but the themes tab always complained about it)
Anyways, I think this shouldn't happen as there is no way to fix it using the UI for me now

**Comment by MrDiamondDog** [comment]
What link did you use? For testing ofc

**Comment by D3SOX** [comment]
I think it also happens with invalid links, for reference here is the relevant part from my Vencord config
```json
{
 "themeLinks": [
        "https://localip.github.io/dark-discord/src/source.css",
        "#https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/css/source.css",
        "#https://KillYoy.github.io/DiscordNight/DiscordNight.css",
        "https://nyri4.github.io/Discolored/main.css",
        "https://d3sox.me/complementary-discord-theme/complementary.theme.css"
    ]
}
```

**Comment by MrDiamondDog** [comment]
I believe it is because of invalid links, which is why I need to make it backwards compatible

**Comment by MrDiamondDog** [comment]
Alright, backwards compatibility should be good now. (@D3SOX)

image

**Comment by D3SOX** [comment]
I could migrate my previously "disabled" themes using `#` in front of the URL now.

image

Other things I noticed:
- I can't add my theme using the GitHub URL (`https://d3sox.github.io/complementary-discord-theme/complementary.theme.css`) because of the redirects and there is no indication why I can't click the `Add` button
image
- I also can't add it using the "real" URL (`https://d3sox.me/complementary-discord-theme/complementary.theme.css`)
image
-  I would show the copy URL button for all themes for sharing purposes

**Comment by MrDiamondDog** [comment]
The URLs are restrictive because of CORS (i think, i'll test), and can you open the console and see if it says anything when you paste the redirect link?

**Comment by MrDiamondDog** [comment]
Well, sites other than the accepted ones seem to work, but I don't think they work on web (need confirmation)

**Comment by D3SOX** [comment]
I'm using Vesktop (Web) and I could previously just put them inside the text box and they worked.
The thing is, CORS fails on the themes page because it uses `fetch` 
image

but when it's inserted into the DOM it loads just fine
image

image

**Comment by MrDiamondDog** [comment]
If you have a CORS error with your theme just add it to quickcss, otherwise it is just a hassle to handle in online themes. This is how it worked before, and I'm going to keep it like this.

**Comment by MrDiamondDog** [comment]
This PR is also ready for review (if anyone would like to)

**Comment by D3SOX** [comment]
I still think this breaks previous behavior as I'm no longer able to add my theme with both links now.

**Comment by MrDiamondDog** [comment]
Did adding other links work before? I thought you said they didn't. The themes that don't work redirect to other websites that are blocked by CORS, hence why they throw errors.

I'm not sure if I want to remove it anymore, I might in the future but I don't see any problems with it actually. The code might honestly be more cluttered if I remove it.

**Comment by D3SOX** [comment]
> Did adding other links work before?

Yes I can just put in the text box. For redirects it says failed to fetch but the theme loads and using the domain works perfectly fine.
image

**Comment by kingofcube** [comment]
how do i add this to my vencord client

**Comment by MrDiamondDog** [comment]
Closed in favor of #2608

**Pull request closed without merging**
