### PR TITLE
feat: add sendify plugin

### PR DESCRIPTION
**Pull request by katlyn**
Adds `/track`, `/album`, and `/artist` commands to send song info to your current channel.

image

### CODE REVIEW

**Comment by Vendicated** [comment]
hardest image ever holy shit

**Comment by Vendicated** [comment]
have u checked if this supports replies?

**Comment by katlyn** [comment]
I hadn't checked, but it doesn't appear to support them - I can look into using the APIs that interactionKeybinds uses to implement it.

**Comment by Vendicated** [comment]
i think all you have to do is
```js
sendMessage(..., {
	referencedMessage: findByprops("getPendingReply").getPendingReply(channelId)
})
```

and dont forget to clear the pending reply

**Comment by Vendicated** [comment]
actually working method
```js
const MessageCreator = lazyWebpack(filters.byProps(["getSendMessageOptionsForReply", "sendMessage"]))
const PendingReplyStore = lazyWebpack(filters.byProps(["getPendingReply"]));

function sendMessage(channelId, message) {
  const reply = PendingReplyStore.getPendingReply(channelId);
  MessageCreator.sendMessage(channelId, message, void 0, MessageCreator.getSendMessageOptionsForReply(reply))
    .then(() => reply && FluxDispatcher.dispatch({ type: "DELETE_PENDING_REPLY", channelId }))
}
```

**Comment by Vendicated** [comment]
neat! Since that sendMessage function is pretty useful, I will probably refactor it to be an exported helper at some point

**Pull request merged**
