### PR TITLE
feat(plugin): Cute Anime Boys

### PR DESCRIPTION
**Pull request by ShadiestGoat**
This adds the plugin to send cute anime boys in a chat. This is a highly important plugin that is extremely useful for all users. This is the #1 reason why I use client side mods.

### CODE REVIEW

**Comment by MeguminSama** [comment]
This will change client modding forever. This is revolutionary.

**Comment by exhq** [comment]
i cummed and shitted and peed at the same time when i saw this pr

**Comment by x6r** [comment]
cute sex with cute boys!!!

**Comment by omaru-ok** [comment]
where is that thign is going?

**Comment by somerandomcloud** [comment]
@Vendicated why isnt this merged???

**Comment by ArjixWasTaken** [comment]
Cursed.

**Comment by Vendicated** [comment]
Thanks! Please see https://discord.com/channels/1015060230222131221/1032200195582197831/1032201093746270238 for why this was closed, feel free to post it there

**Pull request closed without merging**
