### PR TITLE
feat(plugin): Letter emoji shortcuts (for easier typing of the blue letters)

### PR DESCRIPTION
**Pull request by UnmatchedBracket**
This plugin adds easier ways to type the blue letter emojis (`:regional_indicator_*:`).

----------

## Option 1: Autocomplete
Makes e.g. `a` and `aa` suggest 🇦 first, `b` and `bb` suggest 🇧 first, etc.

https://github.com/user-attachments/assets/8a8dc738-6c55-406c-a57b-078a1354eda3

This will not insert the emoji if e.g. `:bb:` is typed.
## Option 2: Alias
Makes typing e.g. `:cc:` correct to 🇨. Single letters like `:c:` don't work to avoid conflicts with 🅰️ and 🅱️.

https://github.com/user-attachments/assets/4d817803-6c90-47ed-83e4-711e96d6d159

Defaults to off due to the side-effect of making the plaintext `:cc:` render as 🇨.
## Option 3: All Letters Autocomplete
Makes `ltr`, `letter`, and `letters` suggest every letter, most useful for typing with reactions/typing lots of letters as emojis.

https://github.com/user-attachments/assets/68efa72d-de72-4e13-8c69-ca232d441c4e

----------
Each option is individually toggleable without reload:
plugin settings popup

### CODE REVIEW

**Comment by Vendicated** [comment]
can be done with the TextReplace plugin already

thanks for your effort though

**Comment by UnmatchedBracket** [comment]
Not entirely, this works in the context of reactions and the emoji picker as well

**Comment by Vendicated** [comment]
too niche then

**Comment by cursefroge** [comment]
partially replicated with this textreplace (regex):
find: `:(?<char>[a-z]):`
replace: `:regional_indicator_$<char>:`

**Pull request closed without merging**
