### PR TITLE
Settings: use nearest-neighbour for shiggy

### PR DESCRIPTION
**Pull request by AppleMayExist**
adds `image-rendering: pixelated` for donate image in Vencord settings if shiggy image is used

### CODE REVIEW

**Comment by Vendicated** [comment]
please show a before and after

**Comment by AppleMayExist** [comment]
Before:
Screenshot from 2023-09-18 16-58-28
After:
Screenshot from 2023-09-18 17-01-00

**Comment by TheKodeToad** [comment]
it doesn't work very well

image

image

**Comment by AppleMayExist** [comment]
Oops, I took the screenshot at like 160% scale or something to exaggerate the effect of the bilinear scaling but it also made the replacement look worse. Here's 100% scale:
Before:
Screenshot from 2023-09-18 17-17-29
After:
Screenshot from 2023-09-18 17-15-14

**Pull request merged**
