### PR TITLE
(SearchReply->BetterSearch): Add Copy Text Button

### PR DESCRIPTION
**Pull request by nmsturcke**
Rename SearchReply to BetterSearch and add a (toggleable) "Copy Text" button to search results:

the plugin in action

### CODE REVIEW

**Comment by Vendicated** [comment]
at this point it might be better to patch discord's code to remove the boolean checks that stop these buttons from being added in the first place instead of adding them manually

**Comment by nmsturcke** [comment]
> at this point it might be better to patch discord's code to remove the boolean checks that stop these buttons from being added in the first place instead of adding them manually

Smart. Will look into it and do it *soon*!

**Comment by Vendicated** [comment]
did you get stuck somewhere? or just forgot?

**Comment by Vendicated** [comment]
superseded by https://github.com/Vendicated/Vencord/commit/c7e5295da0aa7ebea2c2632552abd14187a8d3ad

image

**Pull request closed without merging**
