### PR TITLE
New plugin: ValidUser

### PR DESCRIPTION
**Pull request by Vendicated**
Fetches unknown users on mention hover

https://user-images.githubusercontent.com/45497981/236868964-72ebe645-18eb-41f9-ac98-309a960be77f.mp4

### CODE REVIEW

**Review by mantikafasi — APPROVED** [review]

**Comment by TheKodeToad** [comment]
are you sure you want a video attached with a slur?

**Comment by Vendicated** [comment]
> are you sure you want a video attached with a slur? :E

sorry, I wasn't paying attention to the actual text lol, that channel was convenient for testing because it has so many unknown mentions. I'm too lazy to change the video now

**Comment by TheKodeToad** [comment]
It's quite bad, someone could even report it (idk if it violates github's policies just having a screenshot or video of what someone else said)

**Comment by ItzOnlyAnimal** [comment]
better video that also doesnt have ohnoslur1!!1 :trollface: 

https://github.com/Vendicated/Vencord/assets/24845294/c140a43b-9454-473b-9cee-5fc87c248525

**Pull request merged**
