### PR TITLE
feat(plugin): AmITyping

### PR DESCRIPTION
**Pull request by MrDiamondDog**
Shows if you are typing. Works with all other typing-related plugins

### CODE REVIEW

**Comment by Kodarru** [comment]
Tbh, I don't see a point in this

**Comment by Koishukaze** [comment]
Is there text in your message input? congrats, you are typing!

**Comment by Zippybonzo** [comment]
Seems useless IMO.

**Comment by byeoon** [comment]
I think this plugin is nice, accidentally typed a character in a channel you were lurking in and now you can't tell if others can see that or not

**Comment by MrDiamondDog** [comment]
I made this plugin so you have a very clear indicator of when other people can see you typing, which I personally find useful

**Comment by Kodarru** [comment]
Why don't you add this to third-party plugins instead

**Comment by SerStars** [comment]
> I made this plugin so you have a very clear indicator of when other people can see you typing, which I personally find useful

I understand your point but you can view in the members list if you are typing and even in the network logs, of course it's hard to see yourself if its a long members list with all the scrolling drama, but i think this is more a 3rd party plugin on my personal opinion

**Comment by SerStars** [comment]
> I made this plugin so you have a very clear indicator of when other people can see you typing, which I personally find useful

I understand your point but you can view in the members list if you are typing and even in the network logs, of course it's hard to see yourself if its a long members list with all the scrolling drama, but i think this is more a 3rd party plugin on my personal opinion

**Pull request closed without merging**
