### PR TITLE
fix(MessageLatency): Adjust for Discord kotlin clients

### PR DESCRIPTION
**Pull request by dolfies**

### CODE REVIEW

**Comment by Nuckyz** [comment]
Make this adjus the delay but keep but keep the kotlin client extra message

**Comment by byeoon** [comment]
why do kotlin clients have a 17 day delay?

**Comment by Vendicated** [comment]
because discord

**Comment by dolfies** [comment]
> Make this adjust the delay but keep but keep the kotlin client extra message

done🫡

**Pull request merged**
