### PR TITLE
CustomRPC Toggle

### PR DESCRIPTION
**Pull request by SzyZuu**
adds a button next to your mic so you can quickly toggle CustomRPC without going to the settings :D

### CODE REVIEW

**Comment by Vendicated** [comment]
https://vencord.dev/plugins/GameActivityToggle

**Comment by SzyZuu** [comment]
> https://vencord.dev/plugins/GameActivityToggle

I'm sorry but my changes have a different functionality than game activity toggle. See, if you wanted to use game activity toggle with customrpc, customrpc has to be on all the time, meaning rpc from games won't work properly. The customrpc toggle gives you the ability to activate the customrpc only when you need it. Example:
You have set up customrpc for "Playing Piano", so you want it to be active only when you actually play, but when you're NOT playing you still want others to see your games rpc.

**Comment by Vendicated** [comment]
yes, i was just about to suggest the VencordToolbox. it's a plugin that adds a toolbar button in the top right and lets plugins specify actions there. just add a Custom Rpc toggle there

**Comment by SzyZuu** [comment]
I see, thanks

**Pull request closed without merging**
