### PR TITLE
ShowConnections: Remove "(click to copy/open)" from tooltip

### PR DESCRIPTION
**Pull request by AutumnVN**

### CODE REVIEW

**Comment by TheKodeToad** [comment]
I only added it because there was no toast... i didn't use a toast because it was inconsistent with Discord's ui where they have a balloon 
image

**Comment by Vendicated** [comment]
I did add a toast!

**Review by TheKodeToad — APPROVED** [review]
Another tweak i'd make is replacing (unverified) with a tick icon next to the username but this seems like an improvement!

**Review by Vendicated — APPROVED** [review]

**Comment by Nuckyz** [comment]
I dont like the idea of adding yourself to the plugin author list if you just removed/changed some text, it's missleading that you are one of the plugin authors cuz you barely did a thing

**Comment by jathek** [comment]
It was kind of useful knowing which would be copied vs which would open a tab. Not a huge issue, but there's information lost due to this PR.

**Pull request merged**
