### PR TITLE
reviewDB: Fix avatar z-index

### PR DESCRIPTION
**Pull request by nmsturcke**
Set z-index to 0 for avatars in reviewDB component

## Old
hO1zy

## New
bSv9L

### CODE REVIEW

**Comment by Vendicated** [comment]
how do u even get this? this seems likr a theme issue

**Comment by nmsturcke** [comment]
> how do u even get this? this seems likr a theme issue

Don't have any themes enabled - It's just that the z-index of the avatar class is 1 by default

**Comment by Vendicated** [comment]
but how do u get here? the profile popout is supposed to close when u open the modal

**Comment by nmsturcke** [comment]
> but how do u get here? the profile popout is supposed to close when u open the modal

click on an avatar of a reviewer
https://i.gyazo.com/b4429db1fccd2e9ac2297a0de75b4ed7.mp4

**Comment by TheKodeToad** [comment]
Maybe it's a Chromium issue because it's not happening on Firefox

**Comment by nmsturcke** [comment]
Also: 
6H7cv

**Comment by Vendicated** [comment]
i cannot reproduce any of this at all. Please provide more info about how you're using Discord, what themes and css you're using, etc

This pr is a poor bandaid fix and doesn't actually address the root issue (of not properly closing the profile popout)

**Comment by Vendicated** [comment]
Gonna close this because it's not the right way of fixing it as mentioned above. Please still provide more info / open a proper fix pr if you can figure it out yourself

**Comment by nmsturcke** [comment]
> Gonna close this because it's not the right way of fixing it as mentioned above. Please still provide more info / open a proper fix pr if you can figure it out yourself

For some reason I can't reproduce it now.. Weird because I had been experiencing it for a while and I have not changed anything within Vencord. Although my whole local cache got restored (~~when I got banned~~) so maybe the issue had something to do with that? No clue tbh

**Comment by AutumnVN** [comment]
lol i accidently reproduced this silly with
```css
[class*=animator] {
  transform: none !important;
}
```

**Pull request closed without merging**
