### PR TITLE
style(showHiddenChannels): change modal text

### PR DESCRIPTION
**Pull request by xafn**
* removes 'you don't have permission' text
* changes button text to 'close'

### CODE REVIEW

**Comment by D3SOX** [comment]
I agree with the close button, but why remove that text?

**Comment by somerandomcloud** [comment]
Yeah, why remove the text? Makes it easier to notice if you have access or not. Honestly, some aren't the sharpest tools in the shed and need the extra drop of info

**Comment by D3SOX** [comment]
Can't see the issue because a modal like this is never used to indicate that you **have** access.
I think the text doesn't hurt, only benefits the peeps you mentioned, and it even looks better with it because it looks very empty without.

**Comment by D3SOX** [comment]
I think it's good with the text, maybe add a lock icon to the modal title on the left

**Comment by sneksnake** [comment]
i don't think we should remove the text too
but i renamed the button in my latest pr
https://github.com/Vendicated/Vencord/pull/170

**Pull request closed without merging**
