### PR TITLE
Update Windows Update patcher

### PR DESCRIPTION
**Pull request by Vendicated**
Migrates the Windows update patcher to the electron 17+ method

Untested, testing this is painful

### CODE REVIEW

**Comment by abUwUser** [comment]
maybe you should mark as a draft since it is untested?

**Comment by Vendicated** [comment]
its not a draft

**Comment by abUwUser** [comment]
oh ok

**Comment by Vendicated** [comment]
i should delete this PR after merging for the irony of PR 404 being a http 404

**Comment by Vendicated** [comment]
NOOO you can only delete issues :(

**Comment by ItzOnlyAnimal** [comment]
imagine

**Pull request merged**
