### PR TITLE
fix(MessageLogger): correctly blur spoilered images

### LINKED ISSUE #1815: [Bug] Message Logger will unblur spoiled images.
### Discord Account

_No response_

### What happens when the bug or crash occurs?

When an image is caught by the MessageLogger, if it contains an image that is spoiled it won't be blurred. 

### What is the expected behaviour?

If MessageLogger finds an image that is spoiled it should be blurred. 

### How do you recreate this bug or crash?

1. Upload an image.
2. Tag as spoiled.
3. Send message
4. Delete message
5. Spoiled image will no longer be blurred but still have "Spoiler" in front of it.

### Errors

_No response_

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

### PR DESCRIPTION
**Pull request by k26pl**
Fixes #1815, same as previous pr that i accidentally closed

### CODE REVIEW

**Comment by rozbrajaczpoziomow** [comment]
You know you can just reopen PRs

**Comment by k26pl** [comment]
I deleted the repo so i can't

**Comment by Vendicated** [comment]
seems like lint is failing, please fix!

**Comment by k26pl** [comment]
should be fixed

**Comment by Vendicated** [comment]
thanks

**Pull request merged**
