### PR TITLE
feat(plugin): Urban Dictionary

### PR DESCRIPTION
**Pull request by jewdev**
A plugin that encodes and decodes base64.
I used "btoa" and "atob" functions (which are deprecated) because I can't use Buffer (**explode**).

### CODE REVIEW

**Comment by jewdev** [comment]
made a dictionary plugin with urban dictionary's api.
very cool!
(embed would be even cooler!)
gif

**Comment by Vendicated** [comment]
you can send embeds just fine via SendBotMessage

**Comment by Vendicated** [comment]
Why did you close this? Imo base64 is kinda useless cause why would u ever need to decode b64 in discord, but the urban dictionary one is cool

I just haven't said anything else because you haven't reacted to my last comment

**Comment by jewdev** [comment]
I accidentally deleted the repo and tried to delete one of my private repos lol.
I managed to make it an embed message and didn't commit it yet.

**Comment by Vendicated** [comment]
Oh i see haha, take ur time and just let me know once youre ready

**Comment by jewdev** [comment]
I pushed the Urban Dictionary plugin to the forked repo but it doesn't show the commits here (Probably because I deleted the previous fork 😢).
I'm not sure if I need to make another PR or not.
Please let me know what should I do :)

This is the plugin for now:
urbangif

**Comment by Vendicated** [comment]
I'm not sure, just make a  new pr

**Comment by jewdev** [comment]
Made a new PR (https://github.com/Vendicated/Vencord/pull/222).
Closing this one.

**Pull request closed without merging**
