### PR TITLE
messageTags: Fix duplicate entries & replies

### PR DESCRIPTION
**Pull request by xMufaro**
Fixed so it doesn't always make a second reply with "Invalid sub-command"

Screenshot 2023-04-16 132239

### CODE REVIEW

**Comment by Luna-devv** [comment]
Woops, will look into it

**Comment by Luna-devv** [comment]
nvm this is a PR not a issue

**Comment by Luna-devv** [comment]
Not sure how I've never noticed that before. Question, does anyone have the issue too that `/tags ...` commands are there multiple times? Cuz I do not know how to fix that 
image

**Comment by somerandomcloud** [comment]
> Not sure how I've never noticed that before. Question, does anyone have the issue too that `/tags ...` commands are there multiple times? Cuz I do not know how to fix that 
> image
> 

This has existed for awhile, thought there was a fix already...

**Comment by Vendicated** [comment]
that likely happens due to duplicate ids, each subcommand likely needs its own id

**Comment by xMufaro** [comment]
Wouldn't converting everything to a seperate command fix it?

image

**Comment by xMufaro** [comment]
i think that fixes the problem

**Comment by Vendicated** [comment]
does it work fine with the name as id? discord uses negative numbers, so I just followed suite with normal commands

**Comment by xMufaro** [comment]
yes it works with the name as id. I also included previously given id to the string just in case there would be some compatibility issues in the future. Without that, the subcommands would just duplicate

**Comment by Vendicated** [comment]
Thank you!

**Pull request merged**
