### PR TITLE
Add Windows Batch installation files

### PR DESCRIPTION
**Pull request by X1nto**
I hate working with batch

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
but you said that you prefer batch over powershell....

**Comment by X1nto** [comment]
Powershell is worse :trollface:

**Comment by ArjixWasTaken** [comment]
:troll: looks like powershell scripts are now made #10

**Comment by X1nto** [comment]
HORROR

**Comment by Vendicated** [comment]
:trollface:

**Pull request closed without merging**
