### PR TITLE
Added Plugin: WatchTogetherActivityAdblock

### PR DESCRIPTION
**Pull request by kumpz**
Simple plugin that injects a modified version AdGuard's BlockYouTubeAdsShortcut code into youtube frames.
Basically done, just needs some testing.

### CODE REVIEW

**Comment by ImLvna** [comment]
This plugin looks like it would only work on desktop/vesktop, as it uses electronside code. The plugin file should be suffixed with .desktop.ts

**Comment by kumpz** [comment]
@ImLvna Ah, I see. Thanks for the input!

**Comment by n1ckoates** [comment]
This works very well, thank you for making it! Is there anything else that needs to be done for this to be ready? I noticed there's a lot of CSS styles specified in the script, are all of those necessary for Discord's embed?

**Comment by kumpz** [comment]
Replaced by #2021

**Pull request closed without merging**
