### PR TITLE
FriendshipRanks

### PR DESCRIPTION
**Pull request by cheesesamwich**
Adds badges showcasing how long you have been friends with a user for (if this is too niche/useless then fair enough)

### CODE REVIEW

**Comment by Golonchy** [comment]
"relationship is sprouting
(1 month)"

**Review by nin0-dev — CHANGES_REQUESTED** [review]
you may want to avoid using external hosts for the friendship ranks. use base64 data links 

https://discord.com/channels/1015060230222131221/1015063227299811479/1245003721428172800

**Comment by cheesesamwich** [comment]
> you may want to avoid using external hosts for the friendship ranks
my bad, i'll switch everything over soon ish

**Comment by Sqaaakoi** [comment]
> > you may want to avoid using external hosts for the friendship ranks
> 
> my bad, i'll switch everything over soon ish

while doing so I'd also recommend migrating to SVG icons

**Comment by cheesesamwich** [comment]
> I'd also recommend migrating to SVG icons

is there a big benefit to doing that? i already have the whole system set up with images and i don't think the badge maker i used supports svg, if its that good though then alright

**Comment by Inbestigator** [comment]
> I don't think the badge maker i used supports svg
Discotools (what you used) uses svgs in the background

**Comment by cheesesamwich** [comment]
> Discotools (what you used) uses svgs in the background

so it does lmao, i'll switch to svg then

**Comment by cheesesamwich** [comment]
image
Quick update, started working on migrating to the svg format

**Comment by Inbestigator** [comment]
Can you make the symbol (e.g. the plant) a cutout instead of white? It’d probably look better and more polished

**Comment by cheesesamwich** [comment]
> Can you make the symbol (e.g. the plant) a cutout instead of white? It’d probably look better and more polished

that's not a bad idea, i'll test it out and let you know

**Comment by cheesesamwich** [comment]
> Can you make the symbol (e.g. the plant) a cutout instead of white? It’d probably look better and more polished

its eh, i kinda prefer it the other way

**Comment by Scyye** [comment]
request from someone that has been using this plugin for a little bit, could you add a 6 month icon? 
almost everyone on my friends list ends up having the `burning`, and it would just make it a little more interesting.

**Comment by cheesesamwich** [comment]
> request from someone that has been using this plugin for a little bit, could you add a 6 month icon? almost everyone on my friends list ends up having the `burning`, and it would just make it a little more interesting.

definitely, i didn't even really notice such a gap in the time frames

**Comment by cheesesamwich** [comment]
> request from someone that has been using this plugin for a little bit, could you add a 6 month icon? almost everyone on my friends list ends up having the `burning`, and it would just make it a little more interesting.

Done! sorry it took a while

**Comment by Scyye** [comment]
> > request from someone that has been using this plugin for a little bit, could you add a 6 month icon? almost everyone on my friends list ends up having the `burning`, and it would just make it a little more interesting.
> 
> Done! sorry it took a while

All good lol
thank you<3

**Comment by Scyye** [comment]
For some reason the hover text doesnt work.
image
image

(im hovering the mouse over the badge in the second image)

**Comment by Inbestigator** [comment]
That doesn't look like a FiendshipRanks tooltip problem...

**Comment by cheesesamwich** [comment]
> For some reason the hover text doesnt work

That is intentional, the badge uses a custom component

**Comment by Scyye** [comment]
why not add it normally?

**Comment by cheesesamwich** [comment]
> why not add it normally?

svg support

**Comment by cheesesamwich** [comment]
Pretty sure the badges got borked after doomsday, will fix it soon

**Comment by cheesesamwich** [comment]
Procrastinated for like 5 days then realised it was a 2 line fix, Also added tooltips to the badges

**Pull request closed without merging**
