### PR TITLE
fix(ShowHiddenChannels): better patch & visual bug fix

### PR DESCRIPTION
**Pull request by sneksnake**

### CODE REVIEW

**Review by D3SOX — APPROVED** [review]
LGTM, thx!

**Comment by D3SOX** [comment]
This broke right-clicking on a hidden channel which could previously be used to mute them

**Comment by ArjixWasTaken** [comment]
> This broke right-clicking on a hidden channel which could previously be used to mute them

Uhh...muting a hidden channel is useless, you should instead mention copying the ID of a hidden channel

**Comment by D3SOX** [comment]
> muting a hidden channel is useless

I don't think so, I use it to clean up channels I never use, using the "Hide Muted Channels" option

**Comment by ArjixWasTaken** [comment]
> > muting a hidden channel is useless
> 
> Not really a major issue but I don't think so, I use it to clean up channels I never use, using the "Hide Muted Channels" option

Hmm, then shouldn't we just mark the hidden channels as muted?

Like, it makes sense cause you won't get notifications from them...

**Comment by D3SOX** [comment]
Already fixed by #170

**Pull request merged**
