### PR TITLE
[Plugin] WatchUsers

### PR DESCRIPTION
**Pull request by KillaMeep**
Adds the ability to "watch" a user, which will show a Toast when a user joins or leaves a VC in servers you share with them
image
image

### CODE REVIEW

**Comment by lewisakura** [comment]
This is an extremely creepy plugin which is in direct violation of the plugin rules. There is no legitimate usage for this, you can just ask your friends when they're on if they want you to know. Please do not resubmit this plugin to the repository.

**Comment by KillaMeep** [comment]
The idea of the plugin was to find when friends are in a LFG server, but ok

**Comment by lewisakura** [comment]
Then ask them to message you, don't unconsensually stalk them.

**Comment by RobinRMC** [comment]
<details>
<summary>But I like stalking..</summary>
This is a joke.
</details>

**Pull request closed without merging**
