### PR TITLE
Third Party plugin loading & npm types package

### PR DESCRIPTION
**Pull request by Vendicated**
https://github.com/Vencord/plugin-template

This is already usable, it just loads every .js file in VencordDir/plugins like normal plugins

TODO:
- [ ] Add some way to add plugins via Vencord settings
- [ ] Add an indicator that this is an external plugin & uninstall button to plugins page
- [ ] Plugin updates
- [ ] Add way to force update / disable all plugins to VencordInstaller so people can save themselves

### CODE REVIEW

**Comment by h4rldev** [comment]
:)

**Comment by somerandomcloud** [comment]
if it was ready it would have been merged

**Comment by GhostOps77** [comment]
i want to see this feature in vencord

**Comment by GhostOps77** [comment]
is this atleast in beta stage?

**Comment by lumap** [comment]
no

**Comment by GhostOps77** [comment]
> no

so, this is still in alpha? or pre-alpha?

**Comment by lumap** [comment]
work in progress that no one should be using as it's nowhere near finished

**Pull request closed without merging**
