### PR TITLE
fix(ShowMeYourName) - proper case insensitive name comparison

### PR DESCRIPTION
**Pull request by Jono997**
There seems to be a bug where when a user's name has capital letters, this plugin always acts as if the username and nickname are different. This is my attempt to fix it.

### CODE REVIEW

**Comment by Bloofield** [comment]
> @Bloofield This broke due to your previous PR #2630

Interesting. I assumed usernames would always be lowercase which is why I didn't add the lowercase conversion for usernames

**Comment by Jono997** [comment]
So will this be merged or the other PR reverted?

**Comment by Bloofield** [comment]
@Jono997 This one should be merged. There needs to be a lowercase conversion to prevent duplicate usernames from showing up.

The thought behind the original PR was to prevent nicknames with capitalisation in them from being shown.

**Comment by hideki2k02** [comment]
Up on this. Just waiting for this to get merged so I can make a few changes too

**Comment by Jono997** [comment]
@Vendicated Sorry for bugging you again, but can you please take a look at this?

**Comment by Jono997** [comment]
Well, uh, that's one way to solve the problem.

**Comment by maddie480** [comment]
Uh yeah, that's just a fork I made for myself :sweat_smile: And given that I rebase the branch to keep my Vencord up-to-date, I'm spamming quite a bit here, I'm going to remove the mention

**Pull request merged**
