### PR TITLE
add Snowflake plugin

### PR DESCRIPTION
**Pull request by SamomenX**
https://cute.red-panda.ninja/uwu/1671745918.png
I tried something to get badge idk
Also thank youuu Vocane#4200

### CODE REVIEW

**Comment by somerandomcloud** [comment]
the damn libs and their cute femboy icons, bunch of snowflakes i tell ya

**Comment by AAGaming00** [comment]
more useful than every @mantikafasi plugin

**Comment by mantikafasi** [comment]
wrong

**Comment by Vendicated** [comment]
Not very useful and snowy season is over anyway now. If someone wants this they should do it with css or import it from cdn or github or smth

**Pull request closed without merging**
