### PR TITLE
USRBG: Add nitro banners to voicechat and member list

### PR DESCRIPTION
**Pull request by ImLvna**
# NOTE: This pull request extends #1243, and it is best if that is merged first

In addition, this shuts up stylelint complaining about webkit attributes

image
image

### CODE REVIEW

**Comment by C10udburst** [comment]
out of curiosity, why didn't you open this PR in the https://github.com/AutumnVN/Vencord repo if this extends that PR?

**Comment by somerandomcloud** [comment]
Honestly this should be a plugin on its own but whatevert

**Comment by ImLvna** [comment]
Added support for it to fetch the currently visible member list entries and display their nitro profiles. Plugin abides by ratelimits

> out of curiosity, why didn't you open this PR in the https://github.com/AutumnVN/Vencord repo if this extends that PR?

So I would be able to get the feedback from the vencord repo, not just autumn

> Honestly this should be a plugin on its own but whatevert

Done! Moved to its own plugin that pulls data from the usrbg plugin

**Comment by Vendicated** [comment]
hi! how's the state of this pr? the pr you specify as blocking is long closed

**Pull request closed without merging**
