### PR TITLE
feat(plugin): Auto Scroll

### PR DESCRIPTION
**Pull request by Walcriz**
Adds auto scroll feature to vencord. 

This feature was forked from [BD AutoScroll](https://github.com/hackermare/BD-AutoScroll) that is MIT licensed.

Related to: #1108

### CODE REVIEW

**Comment by Vendicated** [comment]
I'm fairly certain you can achieve this by launching discord with `--enable-blink-features=MiddleClickAutoscroll` so this plugin is obsolete

**Comment by Walcriz** [comment]
Launching discord via the command `discord --enable-blink-features=MiddleClickAutoscroll` doesn't seem to do anything. 

I'm running Arco Linux

**Comment by Walcriz** [comment]
> I'm fairly certain you can achieve this by launching discord with --enable-blink-features=MiddleClickAutoscroll so this plugin is likely obsolete

Yeah it seems you can run discord with `--enable-blink-features=MiddleClickAutoscroll` to get the outcome of this plugin (I was just doing it wrong the first time).

Closing this pull request here even though I can see less technical users be confused on how to enable this.

**Comment by Vendicated** [comment]
thank you anyway!!

**Comment by goat865** [comment]
it does work in terms of scrollig, however it still pastes in the clipboard content. any fix for that?

**Pull request closed without merging**
