### PR TITLE
feat(plugin): Added fakeProfile

### PR DESCRIPTION
**Pull request by sampathgujarathi**
This plugin allows users to use profile effects, themes, animated avatar, banner, avatar decorations without nitro.
image

### CODE REVIEW

**Comment by ryan-0324** [comment]
Duplicate of #1930

**Comment by sampathgujarathi** [comment]
> Duplicate of #1930

In Effecto plugin users dont have to copy 3y3 id and paste it in their bio.

**Comment by FieryFlames** [comment]
> > Duplicate of #1930
> 
> In Effecto plugin users dont have to copy 3y3 id and paste it in their bio.

There's no clear way for users to actually set their own effect though.

**Comment by sampathgujarathi** [comment]
> > > Duplicate of #1930
> > 
> > 
> > In Effecto plugin users dont have to copy 3y3 id and paste it in their bio.
> 
> There's no clear way for users to actually set their own effect though.

Users can to join server and select their profile effects from there, then it will be automatically updated. It's same as USRBG

**Comment by FieryFlames** [comment]
I missed the settingsAboutComponent.. I think the 3y3 version is better, userbg has a reason to use a bot (needs to store images) but this can clearly be done with 3y3.

**Comment by sampathgujarathi** [comment]
> I missed the settingsAboutComponent.. I think the 3y3 version is better, userbg has a reason to use a bot (needs to store images) but this can clearly be done with 3y3.

3y3 is not better because it will take up to 20 characters from about me. I will be making this way more simple after few days

**Comment by ItsCrusaderDude69** [comment]
well i like it

**Comment by Vendicated** [comment]
as i said on discord, this mostly duplicates already existing plugins, and i don't trust you with being responsible for the API, because i don't know you

so i'll be rejecting this. thanks for your efforts regardless

**Pull request closed without merging**
