### PR TITLE
ShowTimeoutDuration: Simplify tooltip style, allow changing style without reload

### PR DESCRIPTION
**Pull request by Sqaaakoi**
The tooltip looked too big and crowded, so I made it simpler

screenshot from my test server

Please do clean up stuff if it is a mess

### CODE REVIEW

**Comment by Vendicated** [comment]
could just replace the original tooltip option instead

**Comment by Sqaaakoi** [comment]
> could just replace the original tooltip option instead

would you recommend that? i'll start working on that now if you'd rather it that way

**Comment by Vendicated** [comment]
why's this still draft?

**Comment by Sqaaakoi** [comment]
yeah i'm only stupid enough to think "hm, maybe this could do with more features" then get overwhelmed trying to reasonably figure out how to make it

**Comment by Sqaaakoi** [comment]
just merge this i'll get around to it in 3-5 business months

**Comment by Nuckyz** [comment]
Very clean! Thanks for the improvements. I took the opportunity to also fix the huge space between the icon and the countdown text

**Pull request merged**
