### PR TITLE
Create MentionChannels

### PR DESCRIPTION
**Pull request by cheesesamwich**
([Plugin Request](https://github.com/Vencord/plugin-requests/issues/11))

### CODE REVIEW

**Comment by TheKodeToad** [comment]
I think shift-clicking would be more useful (like with users)
Maybe the button should be renamed to Mention for consistency too

**Comment by TheKodeToad** [comment]
Take a look at the onclick handler for channel buttons maybe?

**Comment by cheesesamwich** [comment]
> Take a look at the onclick handler for channel buttons maybe?

yeah, i tried that but i couldnt find the react component. Gonna take a look again

**Comment by Vendicated** [comment]
> I think shift-clicking would be more useful (like with users)

That sounds really good

**Comment by Vendicated** [comment]
> yeah, i tried that but i couldnt find the react component. Gonna take a look again

react devtools are your friend.

[Screencast from 2024-02-15 09-40-32.webm](https://github.com/Vendicated/Vencord/assets/45497981/8a7bf2ce-5827-4823-b4e7-31155eadf2e5)

**Comment by cheesesamwich** [comment]
> react devtools are your friend.
i spent like a solid hour trying to do it and unfortunately i am unable to brain 💀

**Pull request closed without merging**
