### PR TITLE
New Plugin: messageCountdown

### PR DESCRIPTION
**Pull request by Kewwie**
A countdown starts when you send a message, you need to wait for it to finish before it can start again

===

Helps people who likes to grind xp in guilds

### CODE REVIEW

**Comment by Baget88** [comment]
AHHH YESS PLEASE ADD THIS, ITS ACTUALLY RLLY GOOD FOR XP 🙏

**Comment by tester5454** [comment]
It's a good plugin why hasn't it been added yet :(
it helped with grinding in guilds and timing rank ups and i think it deserves to be in the plugin store

**Comment by nin0-dev** [comment]
not only is this plugin extremely niche and useless to 99% of people that have a life beyond XP grinding, it also needs to be reviewed before it even is merged

be patient

**Comment by tester5454** [comment]
This plugin's existence is 99% for the people that don't have a life and it's been 2 months how much longer are they gonna take

**Comment by Baget88** [comment]
speaking on behalf of 100people in this server i am in, they want it and so do i
some servers give prizes for getting xp which is another reason that it is useful

**Comment by lewisakura** [comment]
Like nin0 has said, this plugin has zero use outside of grinding bot XP in guilds, and we recently updated our plugin guidelines to ban these sorts of plugins:
> No plugins that interact with specific Discord bots (official Discord apps like Youtube WatchTogether are okay)

Since there was no actual given use case beyond this in the PR description (and the whole plugin is built around the concept of grinding XP based on the settings), I'm going to close and lock this.

**Pull request closed without merging**
