### PR TITLE
feat(plugin): Plex Rich Presence

### PR DESCRIPTION
**Pull request by DevJhoan**
Plugin adds a custom rpc with your current playing from Plex or Emby

msedge_aayqcu2MSh
msedge_oOslFECX6S
msedge_xSkpStUuu6

### CODE REVIEW

**Comment by programminglaboratorys** [comment]
too niche and very complex for a plugin. have you put in mind the user perspective?

**Comment by DevJhoan** [comment]
> too niche and very complex for a plugin. have you put in mind the user perspective?

wdym with "user perspective"?

**Comment by MrDiamondDog** [comment]
> wdym with "user perspective"?

In other words: User Experience. This plugin doesn't make much sense to the average user, and it is really niche as those services aren't used by many people.

I think this would do well as a third party plugin though.

**Comment by happyendermangit** [comment]
Nice plugin, some people use plex and emby so it'll be useful for them...

**Comment by Vendicated** [comment]
sorry but this is too niche.. and quite a lot of code for that

why can't you just use https://github.com/phin05/discord-rich-presence-plex ?

i'll be rejecting this, but thanks for your efforts!

**Pull request closed without merging**
