### PR TITLE
Plugin that removes canary subdomain from message

### PR DESCRIPTION
**Pull request by somerandomcloud**
Small plugin that removes `canary.` from message. Plinko, I guess

### CODE REVIEW

**Comment by Ruthenic** [comment]
possibly make this remove ptb links as well?

**Comment by somerandomcloud** [comment]
Will do now. Plinko, I guess

**Comment by somerandomcloud** [comment]
Updated to remove PTB from onSend event, and also made it check for `discord.` and `discordapp.`

**Comment by somerandomcloud** [comment]
nvm broke it. Plinko, I guess

**Comment by somerandomcloud** [comment]
it workie

**Comment by somerandomcloud** [comment]
To see what this does and doesnt filter, click the below link

**Review by Vendicated — APPROVED** [review]

**Pull request merged**
