### PR TITLE
Fixed spelling/grammar mistakes

### PR DESCRIPTION
**Pull request by ternera**
Hi! I fixed some spelling and grammar mistakes that I found in the documentation.

### CODE REVIEW

**Comment by Vendicated** [comment]
besides the one minor typo, none of the things you changed are mistakes

this just seems like contribution farming

**Comment by Vendicated** [comment]
this documentation is due for a rewrite anyway

**Comment by ternera** [comment]
I considered rewriting some things, but figured I would submit a small PR first and see what the thoughts would be. I'd be happy to clean up more in the readme and other documentation, but would prefer to only spend time on it if it's something that's actually wanted.

**Comment by Vendicated** [comment]
by rewrite i was referring to a full rewrite from scratch, since a lot of it is outdated

but that would have to be done by a seasoned contributor who knows their way around. i've been working on it already

**Pull request closed without merging**
