### PR TITLE
BetterProfileSidebar plugin

### PR DESCRIPTION
**Pull request by D3SOX**
Closes https://github.com/Vencord/plugin-requests/issues/58

# Preview

image

# TODO
- [ ] Auto-expand panels
- [ ] Patch user popouts

Make use of
`UserProfileStore.getMutualGuilds`
`UserProfileStore.getMutualFriends`

### CODE REVIEW

**Comment by Vendicated** [comment]
how does this work when there are 3 million mutual freiends / guilds

**Comment by Vendicated** [comment]
also the linked request asks for this in normal profiles

**Comment by Vendicated** [comment]
> how does this work when there are 3 million mutual freiends / guilds

funny

image

**Comment by D3SOX** [comment]
Yeah, misread the request, have to restructure this a lot.

**Pull request closed without merging**
