### PR TITLE
ModViewBypass plugin

### PR DESCRIPTION
**Pull request by Sqaaakoi**
Unlocks the Mod View menu to be used without moderator permissions, and enables it in every guild (so the user doesn't need to go into experiments to do so)

### CODE REVIEW

**Comment by Vendicated** [comment]
could you describe the use case?

**Comment by Sqaaakoi** [comment]
> could you describe the use case?

I often find myself using mod view in guilds I am not a moderator in to see if someone is a troll who has been in the guild for a long time but has sent little to no messages. The built-in filtering of notable permissions and roles with permissions is also nice to have as a member.

**Comment by ac-tu** [comment]
How can you enable it with experiments? Considering this may not get merged. Despite its quality of life use.

**Comment by ac-tu** [comment]
> But this only enables mod view for servers you have mod permissions in. The extension enables this and gives you it in servers you don't have mod permissions in.

Oh unfortunate that you can't enable it despite perms, either way that experiement is useful, thank you!

**Comment by thewilloftheshadow** [comment]
Mod view has been rolled out to all servers now

**Comment by Sqaaakoi** [comment]
> Mod view has been rolled out to all servers now

well they changed something that actually affects the main functionality, I have to fix that patch (I only just noticed today)

**Comment by Vendicated** [comment]
superseded by https://github.com/Vendicated/Vencord/pull/2415

thanks regardless!

**Pull request closed without merging**
