### PR TITLE
Update quickCss.ts

### PR DESCRIPTION
**Pull request by LaptopCat**
fixes really really tiny issue that would update the style when editing quickcss even though quickcss is disabled in settings

### CODE REVIEW

**Comment by Vendicated** [comment]
hello!

how exactly is this an issue? does style.disabled not prevent the css from having any effect?

**Comment by LaptopCat** [comment]
https://github.com/Vendicated/Vencord/assets/98688203/0a755041-875f-4a51-aee2-d141a5ac3af7

**Comment by LaptopCat** [comment]
steps to reproduce issue:

1. disable custom css (quickcss) in settings
if you didnt have it enabled, enable it and then disable it

2. click on the "open quickcss file" button

3. edit something

4. changes get applied, though custom css is disabled

**Comment by Vendicated** [comment]
Thank you! This seems to be a bug / quirky oversight in the html spec
For some reason setting style.textContent resets style.disabled

In any case, this fix is not optimal because it will potentially lead to stale content. I have pushed a better fix in https://github.com/Vendicated/Vencord/commit/2a318e390e77f8269fcba45ab9a0fd7008ca8d0a

**Pull request closed without merging**
