### PR TITLE
new plugin: OverrideForumDefaults

### PR DESCRIPTION
**Pull request by Inbestigator**
OverrideForumDefaults lets you set the default layout/sort order of a forum instead of relying on moderator choices. You can still change the settings on a per-channel basis.

image

[Original plugin suggestion](https://github.com/Vencord/plugin-requests/issues/195)

### CODE REVIEW

**Review by MrDiamondDog — COMMENTED** [review]
Imo I would make it per-channel, and have a button in the context menu to change it

**Comment by Inbestigator** [comment]
> Imo I would make it per-channel, and have a button in the context menu to change it

The pull request said that they wanted it to be global, and I think that's probably a good option, you're still able to change the view on a per-channel basis. The plugin is just overriding the default.

**Comment by MrDiamondDog** [comment]
Oh ok

**Comment by Vendicated** [comment]
thanks!

**Pull request merged**
