### PR TITLE
SpotifyControls: export album cover as CSS variable for themes

### PR DESCRIPTION
**Pull request by Av32000**
I've added (as an option) the cover of the album/track currently playing to the SpotifyControl plugin player
Preview : 
image

### CODE REVIEW

**Comment by Oi-jojo** [comment]
thanks, i will be using this lol

**Comment by Av32000** [comment]
> image
> 
> Contrast might become a problem with light covers

Do you have any idea how to solve this problem?

**Comment by cheesesamwich** [comment]
> Do you have any idea how to solve this problem?
you could make the buttons use an invert filter? or something like that

**Comment by D3SOX** [comment]
The other ones were actually custom icons from my CSS but here it's barely readable for the text too. The rotating makes it less bad as it's not always the case when it's not fully white

image

**Comment by Vendicated** [comment]
i don't think this is a good addition. way too opiniated no matter how you implement it. it should imo instead be left to themes. the plugin would just need to expose the album cover url as a css variable on the player, then any theme can do whatever they want

**Comment by D3SOX** [comment]
I like @Vendicated's idea. Would you change this PR to only do this and then provide your CSS as a theme in your own repo.

**Comment by Av32000** [comment]
It's done !
The new css var is `--vc-spotify-track-image`

**Comment by Vendicated** [comment]
thanks! pretty cool. works nicely

```css
#vc-spotify-player {
    background: linear-gradient(
          rgba(0, 0, 0, 0.7), 
          rgba(0, 0, 0, 0.7)
        ), var(--vc-spotify-track-image) !important;
    background-size: cover !important;
}
```

image
image

**Pull request merged**
