### PR TITLE
TimeBarAllActivities: Support new activity cards

### PR DESCRIPTION
**Pull request by hauntii**
Discord recently updated the activity cards on profiles to a new design, and changed how the Spotify activity appears. It is no longer an optional feature of all cards, and is a separate card.

This update adds the time bar component to the new standard activity cards if they have valid timestamps.

It also adds options for hiding the "badges" on the cards (game controller/tv with the elapsed time) and the `large_text` attribute on listening activities, making it look like the Spotify card, as it no longer shows that information (unless the album art is hovered).

### CODE REVIEW

**Comment by fawni** [comment]
was messing around trying to debug why it broke and discovered the same thing. glad i checked prs!

LGTM

**Comment by hauntii** [comment]
Resolved reviews automatically, should be all good to go now!

**Comment by Nuckyz** [comment]
One last thing, add a picture to the README. You can upload it here and copy the link https://github.com/Vendicated/Vencord/issues/1749

**Review by Nuckyz — APPROVED** [review]

**Comment by Nuckyz** [comment]
Thank you for the contribution!

**Pull request merged**
