### PR TITLE
PatootiesEpicPlugin

### PR DESCRIPTION
**Pull request by E-boi**
an epic plugin by patootie

### CODE REVIEW

**Comment by Jacob1Tm** [comment]
That sounds like a great plugin to use on public discord server :)

**Comment by somerandomcloud** [comment]
bro wtf is this plugin :sob:

**Comment by JaideAirblade** [comment]
just one that makes you randomly share/giveaway your discord account

**Comment by Jacob1Tm** [comment]
Exactly! Great fun, I love that plugin.

**Comment by somerandomcloud** [comment]
Can this plugin also give away my address with a 1/10000 chance?

**Comment by somerandomcloud** [comment]
At that point it is a 1/111 chance

**Review by TymanWasTaken — APPROVED** [review]
LGTM, will use

**Comment by Lisenaaaa** [comment]
the best plugin
but it would be better if it sent your social security number also

**Review by MeguminSama — CHANGES_REQUESTED** [review]
As funny as this is... I'm not sure it's a great idea to include it lol

**Comment by BanTheNons** [comment]
Why though? If anybody actually enables it after reading the description it's their fault

**Comment by MeguminSama** [comment]
something something discord will get pissed off if we include a token leaker in our mod 💀

**Comment by E-boi** [comment]
NOOOOoo its such a good plugin tho

**Pull request closed without merging**
