### PR TITLE
fix misinformation

### PR DESCRIPTION
**Pull request by mantikafasi**

### CODE REVIEW

**Comment by Vendicated** [comment]
BetterUploadButton

**Comment by mantikafasi** [comment]
better upload button is not standart behaivour

**Comment by Vendicated** [comment]
oh true i thought it was the reverse, as in you have the plugin enabled and are complaining it's wrong for you

**Comment by nin0-dev** [comment]
what if the description changed based on if you had betteruploadbutton enabled 🚀

**Comment by KrstlSkll69** [comment]
> what if the description changed based on if you had betteruploadbutton enabled 🚀

**Comment by jamesbt365** [comment]
Any interest in reopening and merging this? The default behaviour (left click) without any plugins in my opinion should be listed as more people are not going to be using BetterUploadButton than are using the plugin.

**Comment by mantikafasi** [comment]
@Vendicated merge

20 Eki 2024 Paz 17:43 tarihinde jamesbt365 ***@***.***> şunu
yazdı:

**Pull request closed without merging**
