### PR TITLE
lastfmRPC: add setting to toggle "View Song" button

### PR DESCRIPTION
**Pull request by Yumiro**
adds support for toggling the "Show Song" button, fixes inconsistent casing in description labels and changes the plugin description a bit.

closes https://github.com/Vencord/plugin-requests/issues/227

### CODE REVIEW

**Comment by Yumiro** [comment]
okay so this is very confusing. i was testing this again today and i noticed some weird interactions: when spotify's rpc shows up, the lastfm rpc goes away, even with the "Hide with Spotify" option disabled, and it shows up as soon as i pause the song. the lastfm rpc also shows up fine if i disable spotify's rpc in discord's connections settings page. this was all tested on stock stable (desktop & web), as the rpc shows up regardless on the client with the plugin enabled. could be a discord bug? really not sure what's going on and would appreciate some help

**Comment by Vendicated** [comment]
can you still reproduce the issue you mentioned? if not, this seems mergeable

but please undo the unrelated changes to the descriptions. all those strings are converted to full caps anyway so it doesnt change anything and just adds noise

**Comment by Yumiro** [comment]
> can you still reproduce the issue you mentioned? if not, this seems mergeable

honestly looking back i might've been stupid and forgot to rebuild after the second commit or something, but it seems to work now after testing with people

> but please undo the unrelated changes to the descriptions. all those strings are converted to full caps anyway so it doesnt change anything and just adds noise

yep sounds good, i've gone ahead and reverted all of that

**Comment by Vendicated** [comment]
thanks!

**Pull request merged**
