### PR TITLE
Plugin: ThemeRepo

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
## About

A generic theme store.

For now it only has better discord's theme store, but more are planned to be added in the future.
(DM me any store you want added)

TODO:
- [ ] Finish the search UI
- - [X] Paginate on scroll
- - [ ] Add buttons to the theme cards
- - [x] Add filters
- - - [ ] Query
- - - [x] Tags
- - - [ ] Sort-By
- - [ ] Show popup when user clicks theme
- - [ ] Indicate if a theme is installed or not
- [ ] Actually install themes

and possibly much more

## Screenshots

*Screenshots will be updated to reflect any changes*

image

### CODE REVIEW

**Comment by mantikafasi** [comment]
reminded me devilbro

**Comment by TheKodeToad** [comment]
Wouldn't it make more sense to have this in Vencord settings?

**Comment by ArjixWasTaken** [comment]
> Wouldn't it make more sense to have this in Vencord settings?

I am all for it, the issue is that I don't really know how to go about doing that.
There is no such API within vencord and vencord should not have plugin related code in the core.

**Comment by TheKodeToad** [comment]
Well, does this need to be a plugin?

**Comment by ArjixWasTaken** [comment]
Yes because ven finds this stupid

**Comment by TheKodeToad** [comment]
Can it not be toggleable?

**Comment by mantikafasi** [comment]
I hate github spamming me new emails about this because I wrote a single comment

**Comment by ArjixWasTaken** [comment]
> I hate github spamming me new emails about this because I wrote a single comment

image

**Comment by MeguminSama** [comment]
unsubscribe from the thread then

**Comment by TheKodeToad** [comment]
Yeah, also you can have the notifications in-app if you don't want emails at all

**Comment by mantikafasi** [comment]
I just did and it resubscribed because I commented again :skull:

**Comment by somerandomcloud** [comment]
> I just did and it resubscribed because I commented again skull

You are so fucking lazy jesus christ

image

**Pull request closed without merging**
