### PR TITLE
Add RemoveNitroAds plugin

### PR DESCRIPTION
**Pull request by ayes-web**
Adds a plugin that removes gift button and nitro button from dm list

### CODE REVIEW

**Review by MeguminSama — CHANGES_REQUESTED** [review]

**Comment by Vendicated** [comment]
Thank you! However I don't really see the point of this because this is easier done with css and that won't break in the future. It also doesn't even cover all cases, there is for example still an obnoxious header on top of people's banners

**Comment by ayes-web** [comment]
> Thank you! However I don't really see the point of this because this is easier done with css and that won't break in the future. It also doesn't even cover all cases, there is for example still an obnoxious header on top of people's banners

I feel like being able to easily configure which parts i want turned off is an improvement over CSS, you can't really do that with a CSS theme (without modifying the theme itself manually)

**Comment by Vendicated** [comment]
Someone could make a css toggler that lets you add and toggle css snippets

**Comment by ayes-web** [comment]
> Someone could make a css toggler that lets you add and toggle css snippets

Pretty good idea, might make it myself

**Comment by Vendicated** [comment]
that'd be awesome, I can help you with that if you want

**Comment by ayes-web** [comment]
Yeah sure :)
I guess i will close this PR and make a new one later

**Pull request closed without merging**
