### PR TITLE
feat(plugin): FavoriteAnything

### PR DESCRIPTION
**Pull request by MrDiamondDog**
Cause of discord's silly code I had to change how the favorite gifs menu is rendered and re-make parts of how the favorite accessory works

### CODE REVIEW

**Comment by kingofcube** [comment]
ok this just lags the discord website for me

**Comment by PortalRex** [comment]
Any chance of getting different media categories?

**Comment by MrDiamondDog** [comment]
> Any chance of getting different media categories?

This plugin was only intended to let you favorite other types of media, so no.

**Comment by MrDiamondDog** [comment]
@CodiumAI-Agent /review

**Comment by MrDiamondDog** [comment]
gonna redo this in a very different way

**Comment by Vlackmaybe** [comment]
please continue this pr

**Comment by Ransomwave** [comment]
Why was this closed????

**Comment by TesterHere06** [comment]
Any chance of this being real eventually?

**Pull request closed without merging**
