### PR TITLE
feat(plugin): Ignore Activities

### PR DESCRIPTION
**Pull request by Nuckyz**

### CODE REVIEW

**Comment by Vendicated** [comment]
Please document this a bit better or try to simplify it. For example, for the long patches array, you could add a comment above each line shortly stating what exactly this is replacing. Otherwise this is gonna be hell to maintain!

**Comment by Nuckyz** [comment]
> Please document this a bit better or try to simplify it. For example, for the long patches array, you could add a comment above each line shortly stating what exactly this is replacing. Otherwise this is gonna be hell to maintain!

yes sir

**Comment by Nuckyz** [comment]
It's done

**Comment by Vendicated** [comment]
why does that sound so mischievous

**Comment by Nuckyz** [comment]
> why does that sound so mischievous

:kekw:

**Review by Vendicated — APPROVED** [review]
Okay im gonna be real I have no idea what's going on but it probably hopefully works

**Pull request merged**
