### PR TITLE
feat(userVoiceShow): Add button to view voice channel without joining

### PR DESCRIPTION
**Pull request by LordEliasTM**
title says it
merge if cute
image

### CODE REVIEW

**Comment by D3SOX** [comment]
Should probably remove the `console.log` and clicking the button doesn't work for me on Vesktop with Discord Stable. Maybe the `transitionTo` or something else is different in Discord Web.
 
image

**Comment by LordEliasTM** [comment]
Fixed all errors and did some cleanup. Ready to merge

**Review by D3SOX — APPROVED** [review]
Works fine for me now :+1:

**Comment by Soulivan71** [comment]
@D3SOX this is not push yet right ?

**Pull request closed without merging**
