### PR TITLE
fxTwitter (plugin)

### PR DESCRIPTION
**Pull request by somerandomcloud**
- **VxTwitter** || Uses VxTwitter to fix embeds from twitter on send
- Added `Dev.Samu` to `src/utils/constants.ts`

### CODE REVIEW

**Comment by somerandomcloud** [comment]
Renamed to fxtwitter and changed url to fxtwitter because <:trolley:1024751352028602449>

**Comment by iGerman00** [comment]
> Renamed to fxtwitter and changed url to fxtwitter because <:trolley:1024751352028602449>

As per the recently added [code of conduct](https://github.com/Vendicated/Vencord/blob/main/CODE_OF_CONDUCT.md) maybe not do that and actually and give an option? Tired of keeping up a custom plugin mod and re-building it just because someone decided to troll.

**Comment by Vendicated** [comment]
What exactly do you mean by that? In any case, this plugin will be superseded by #540 soon anyway

**Comment by iGerman00** [comment]
Fair enough about being superseded, I didn't see that - that'll probably stop the need for rebuilding. Still, really not nice to just shut anyone down who's suggesting vxtwitter be added. If it's suggested - clearly, it's wanted. Felt hypocritical to me ever since I saw it. With no easy user plugins without rebuilding the whole thing. It's really annoying that just because someone said ":trollface:" I had to rebuild ever since.

**Comment by Vendicated** [comment]
I've said from the very start that these kinds of plugins are bad because they will always be opionated and shouldn't exist, and you can find this on multiple PR's touching this plugin! Just wait for text replace, then it will be fully customisable

**Comment by iGerman00** [comment]
> will always be opionated

It's not about opinions, it's about options. There are about 8 billion opinions. If someone asks for something different why not just use a toggle... It took me about 5 minutes to add one with little coding experience, but I didn't bother suggesting it because everyone here seems to really hate the idea of it. Clearly the same single alternative was suggested, not hundreds of them, so there's really no reason for being so stuck on using just one of them because it's "objectively better". A toggle would've sufficed. Just sayin'

**Comment by somerandomcloud** [comment]
lmfao? why did you dig to this pr just to complain about an ancient and soon-to-be replaced plugin? how would it comply with the coc if it was created months before the coc? honestly just a lot of copium for no reason...

**Comment by iGerman00** [comment]
because it bothers me, it's that easy, and you are still a troll too

**Comment by somerandomcloud** [comment]
how am i a troll? it was just a silly light-hearted comment or whatever you are referring to... the plugin was a dirty fix for someone in the discord server, and i  was recommended to use fxtwitter instead of vxtwitter on the discord by vendicated himself because its ***subjectively*** better (better embed on discord, backend is more trustworthy, etc...)

**Comment by iGerman00** [comment]
it's not that hard to not be stuck up about it and just add an option when 3 different people and probably more mentioned it across various PRs, yeesh. it's not that deep.

**Pull request merged**
