### PR TITLE
Prevent videos playing in modal with NoMosaic

### PR DESCRIPTION
**Pull request by TheKodeToad**

### CODE REVIEW

**Comment by TheKodeToad** [comment]
Huh looks like this also disables the carousel. Maybe I should make it more specific and split into multiple options.

**Comment by Cynosphere** [comment]
```js
{
  find: /poster:\i\.toString\(\),naturalWidth/,
  replacement: {
    match: /\i\[(\i)\.src\]=function\(\i\){return \i\(\i,\i,\i,\i\)}/,
    replace: (orig, state) => `if(!${state}?.component?.props?.poster)${orig}`
  },
}
```

**Comment by TheKodeToad** [comment]
what?

**Comment by Cynosphere** [comment]
Patch that allows playing videos inline without disabling carousel entirely

**Comment by TheKodeToad** [comment]
thinking about it carousel doesn't make as much sense if clicking the video doesn't open it

**Pull request closed without merging**
