### PR TITLE
spotifyControls: make album of local tracks unclickable

### PR DESCRIPTION
**Pull request by janisslsm**
clicking album of local track will open https://open.spotify.com/album/null. this pr fixes it.

### CODE REVIEW

**Comment by Vendicated** [comment]
local tracks can have an album?

**Comment by janisslsm** [comment]
> local tracks can have an album?

yes, it gets it from tags. here's an example
image

**Comment by Vendicated** [comment]
alibaba

**Comment by janisslsm** [comment]
yes, top tier name.

**Comment by Vendicated** [comment]
<:trolley:916000825325780992>

**Comment by D3SOX** [comment]
> local tracks can have an album? 

Yes I thought about this too but I forgot to push it in my previous PR

**Pull request merged**
